version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_frontend
    args:
        UID: ${UID}
        GID: ${GID}
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      project-network:
        aliases:
          - frontend.local
    command: npm run dev
networks:
  project-network:
    name: project-network-shared
    driver: bridge
